
import "./globals.css";
import ButtonAppBar from "../components/topbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ButtonAppBar />
        {children}
      </body>
    </html>
  );
}
